[vulndb]
db.path = '~/.vulndb/vuln.db'
# nvd_api_key = 'your-api-key'
request_delay = 6

## The maximum number of attempts
## For infinite number of attempts set it to -1
#retry_tries = 10  

## The maximum value of delay in seconds
#retry_max_delay = 30

## Multiplier applied to delay between attempts
#retry_backoff = 3
